- name: install db
  hosts: db
  become: yes
  vars:
    login_host: db.devopsbhaskar.online
  tasks:
  - name: install MySQL
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: Enable and start MySQL
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{ login_host }}"
      filter: version
    ignore_erros: yes
    register: msql_connection_output

  - name: print output
    ansible.builtin.debug:
      msg: "sql output"
