- name: install frontend  
  hosts: frontend 
  become: yes
  vars:
  tasks:
  - name: Install nginx
    ansible.builtin.command: dnf install nginx -y 

  - name: Enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: start
      enabled: yes