- name: install frontend  
  hosts: frontend 
  vars:
  tasks:
  - name: Install nginx
    ansible.builtin.command: dnf install nginx -y 
  - name: Enable and start nginx
    ansible.builtin.dnf:
      name: nginx
      state: started
      enabled: yes


